---
- hosts: hadoop_master
  tasks:
  - name: Copy workers file to hadoop-master
    ansible.builtin.copy:
      src: hadoop-master/workers
      dest: /home/ec2-user/hadoop-3.3.6/etc/hadoop/workers

  - name: copy hdfs-site.xml file to hadoop-master
    ansible.builtin.copy:
      src: hadoop-master/hdfs-site.xml
      dest: /home/ec2-user/hadoop-3.3.6/etc/hadoop/hdfs-site.xml

  - name: Create NameNode metadata path
    ansible.builtin.file:
      path: /home/ec2-user/nn
      state: directory

  - name: Format the NameNode directory
    ansible.builtin.shell: /home/ec2-user/hadoop-3.3.6/bin/hdfs namenode -format -force

  - name: Copy namenode.service file to hadoop-master
    ansible.builtin.copy:
      src: hadoop-master/namenode.service
      dest: /tmp/namenode.service

  - name: Copy namenode.service to the proper location
    ansible.builtin.shell: sudo cp /tmp/namenode.service /etc/systemd/system/namenode.service

  - name: Start NameNode
    ansible.builtin.shell: sudo systemctl start namenode

  - name: Set the service to start at init
    ansible.builtin.shell: sudo systemctl enable namenode