- hosts: hadoop_worker
  tasks:
  - name: copy hdfs-site.xml file to hadoop-worker
    ansible.builtin.copy:
      src: hadoop-worker/hdfs-site.xml
      dest: /home/ec2-user/hadoop-3.3.6/etc/hadoop/hdfs-site.xml

  - name: Create DataNode directory
    ansible.builtin.file:
      path: /home/ec2-user/dn
      state: directory

  - name: Copy datanode.service file to hadoop-worker
    ansible.builtin.copy:
      src: hadoop-worker/datanode.service
      dest: /tmp/datanode.service

  - name: Copy datanode.service to the proper location
    ansible.builtin.shell: sudo cp /tmp/datanode.service /etc/systemd/system/datanode.service

  - name: Start DataNode
    ansible.builtin.shell: sudo systemctl start datanode

  - name: Set the service to start at init
    ansible.builtin.shell: sudo systemctl enable datanode